/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as AuthenticatedTornarSeLojistaRouteImport } from './routes/_authenticated/tornar-se-lojista'
import { Route as AuthenticatedTornarSeEntregadorRouteImport } from './routes/_authenticated/tornar-se-entregador'
import { Route as AuthenticatedPagamentosRouteImport } from './routes/_authenticated/pagamentos'
import { Route as AuthenticatedEnderecosRouteImport } from './routes/_authenticated/enderecos'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedAdmRouteImport } from './routes/_authenticated/adm'
import { Route as AuthenticatedPedidosIndexRouteImport } from './routes/_authenticated/pedidos/index'
import { Route as AuthenticatedLojistaIndexRouteImport } from './routes/_authenticated/lojista/index'
import { Route as AuthenticatedEntregadorIndexRouteImport } from './routes/_authenticated/entregador/index'
import { Route as ApiPublicCourierApplicationRouteImport } from './routes/api/public/courier-application'
import { Route as AuthenticatedPedidosIdRouteImport } from './routes/_authenticated/pedidos/$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTornarSeLojistaRoute =
  AuthenticatedTornarSeLojistaRouteImport.update({
    id: '/tornar-se-lojista',
    path: '/tornar-se-lojista',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTornarSeEntregadorRoute =
  AuthenticatedTornarSeEntregadorRouteImport.update({
    id: '/tornar-se-entregador',
    path: '/tornar-se-entregador',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPagamentosRoute = AuthenticatedPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEnderecosRoute = AuthenticatedEnderecosRouteImport.update({
  id: '/enderecos',
  path: '/enderecos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdmRoute = AuthenticatedAdmRouteImport.update({
  id: '/adm',
  path: '/adm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosIndexRoute =
  AuthenticatedPedidosIndexRouteImport.update({
    id: '/pedidos/',
    path: '/pedidos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLojistaIndexRoute =
  AuthenticatedLojistaIndexRouteImport.update({
    id: '/lojista/',
    path: '/lojista/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntregadorIndexRoute =
  AuthenticatedEntregadorIndexRouteImport.update({
    id: '/entregador/',
    path: '/entregador/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCourierApplicationRoute =
  ApiPublicCourierApplicationRouteImport.update({
    id: '/api/public/courier-application',
    path: '/api/public/courier-application',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPedidosIdRoute = AuthenticatedPedidosIdRouteImport.update({
  id: '/pedidos/$id',
  path: '/pedidos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/adm': typeof AuthenticatedAdmRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/enderecos': typeof AuthenticatedEnderecosRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/tornar-se-entregador': typeof AuthenticatedTornarSeEntregadorRoute
  '/tornar-se-lojista': typeof AuthenticatedTornarSeLojistaRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/api/public/courier-application': typeof ApiPublicCourierApplicationRoute
  '/entregador/': typeof AuthenticatedEntregadorIndexRoute
  '/lojista/': typeof AuthenticatedLojistaIndexRoute
  '/pedidos/': typeof AuthenticatedPedidosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/adm': typeof AuthenticatedAdmRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/enderecos': typeof AuthenticatedEnderecosRoute
  '/pagamentos': typeof AuthenticatedPagamentosRoute
  '/tornar-se-entregador': typeof AuthenticatedTornarSeEntregadorRoute
  '/tornar-se-lojista': typeof AuthenticatedTornarSeLojistaRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/api/public/courier-application': typeof ApiPublicCourierApplicationRoute
  '/entregador': typeof AuthenticatedEntregadorIndexRoute
  '/lojista': typeof AuthenticatedLojistaIndexRoute
  '/pedidos': typeof AuthenticatedPedidosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/adm': typeof AuthenticatedAdmRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/enderecos': typeof AuthenticatedEnderecosRoute
  '/_authenticated/pagamentos': typeof AuthenticatedPagamentosRoute
  '/_authenticated/tornar-se-entregador': typeof AuthenticatedTornarSeEntregadorRoute
  '/_authenticated/tornar-se-lojista': typeof AuthenticatedTornarSeLojistaRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/_authenticated/pedidos/$id': typeof AuthenticatedPedidosIdRoute
  '/api/public/courier-application': typeof ApiPublicCourierApplicationRoute
  '/_authenticated/entregador/': typeof AuthenticatedEntregadorIndexRoute
  '/_authenticated/lojista/': typeof AuthenticatedLojistaIndexRoute
  '/_authenticated/pedidos/': typeof AuthenticatedPedidosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/adm'
    | '/checkout'
    | '/enderecos'
    | '/pagamentos'
    | '/tornar-se-entregador'
    | '/tornar-se-lojista'
    | '/loja/$slug'
    | '/pedidos/$id'
    | '/api/public/courier-application'
    | '/entregador/'
    | '/lojista/'
    | '/pedidos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/adm'
    | '/checkout'
    | '/enderecos'
    | '/pagamentos'
    | '/tornar-se-entregador'
    | '/tornar-se-lojista'
    | '/loja/$slug'
    | '/pedidos/$id'
    | '/api/public/courier-application'
    | '/entregador'
    | '/lojista'
    | '/pedidos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/adm'
    | '/_authenticated/checkout'
    | '/_authenticated/enderecos'
    | '/_authenticated/pagamentos'
    | '/_authenticated/tornar-se-entregador'
    | '/_authenticated/tornar-se-lojista'
    | '/loja/$slug'
    | '/_authenticated/pedidos/$id'
    | '/api/public/courier-application'
    | '/_authenticated/entregador/'
    | '/_authenticated/lojista/'
    | '/_authenticated/pedidos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LojaSlugRoute: typeof LojaSlugRoute
  ApiPublicCourierApplicationRoute: typeof ApiPublicCourierApplicationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tornar-se-lojista': {
      id: '/_authenticated/tornar-se-lojista'
      path: '/tornar-se-lojista'
      fullPath: '/tornar-se-lojista'
      preLoaderRoute: typeof AuthenticatedTornarSeLojistaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tornar-se-entregador': {
      id: '/_authenticated/tornar-se-entregador'
      path: '/tornar-se-entregador'
      fullPath: '/tornar-se-entregador'
      preLoaderRoute: typeof AuthenticatedTornarSeEntregadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pagamentos': {
      id: '/_authenticated/pagamentos'
      path: '/pagamentos'
      fullPath: '/pagamentos'
      preLoaderRoute: typeof AuthenticatedPagamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/enderecos': {
      id: '/_authenticated/enderecos'
      path: '/enderecos'
      fullPath: '/enderecos'
      preLoaderRoute: typeof AuthenticatedEnderecosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/adm': {
      id: '/_authenticated/adm'
      path: '/adm'
      fullPath: '/adm'
      preLoaderRoute: typeof AuthenticatedAdmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos/': {
      id: '/_authenticated/pedidos/'
      path: '/pedidos'
      fullPath: '/pedidos/'
      preLoaderRoute: typeof AuthenticatedPedidosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lojista/': {
      id: '/_authenticated/lojista/'
      path: '/lojista'
      fullPath: '/lojista/'
      preLoaderRoute: typeof AuthenticatedLojistaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/entregador/': {
      id: '/_authenticated/entregador/'
      path: '/entregador'
      fullPath: '/entregador/'
      preLoaderRoute: typeof AuthenticatedEntregadorIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/courier-application': {
      id: '/api/public/courier-application'
      path: '/api/public/courier-application'
      fullPath: '/api/public/courier-application'
      preLoaderRoute: typeof ApiPublicCourierApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/pedidos/$id': {
      id: '/_authenticated/pedidos/$id'
      path: '/pedidos/$id'
      fullPath: '/pedidos/$id'
      preLoaderRoute: typeof AuthenticatedPedidosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdmRoute: typeof AuthenticatedAdmRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedEnderecosRoute: typeof AuthenticatedEnderecosRoute
  AuthenticatedPagamentosRoute: typeof AuthenticatedPagamentosRoute
  AuthenticatedTornarSeEntregadorRoute: typeof AuthenticatedTornarSeEntregadorRoute
  AuthenticatedTornarSeLojistaRoute: typeof AuthenticatedTornarSeLojistaRoute
  AuthenticatedPedidosIdRoute: typeof AuthenticatedPedidosIdRoute
  AuthenticatedEntregadorIndexRoute: typeof AuthenticatedEntregadorIndexRoute
  AuthenticatedLojistaIndexRoute: typeof AuthenticatedLojistaIndexRoute
  AuthenticatedPedidosIndexRoute: typeof AuthenticatedPedidosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdmRoute: AuthenticatedAdmRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedEnderecosRoute: AuthenticatedEnderecosRoute,
  AuthenticatedPagamentosRoute: AuthenticatedPagamentosRoute,
  AuthenticatedTornarSeEntregadorRoute: AuthenticatedTornarSeEntregadorRoute,
  AuthenticatedTornarSeLojistaRoute: AuthenticatedTornarSeLojistaRoute,
  AuthenticatedPedidosIdRoute: AuthenticatedPedidosIdRoute,
  AuthenticatedEntregadorIndexRoute: AuthenticatedEntregadorIndexRoute,
  AuthenticatedLojistaIndexRoute: AuthenticatedLojistaIndexRoute,
  AuthenticatedPedidosIndexRoute: AuthenticatedPedidosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LojaSlugRoute: LojaSlugRoute,
  ApiPublicCourierApplicationRoute: ApiPublicCourierApplicationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
